title: Jacian's Blog
subtitle: Jacian's Blog
description: ''
keywords: "Jacian,Java,MySQL,Blog,博客,Jacian's Blog"
author: Jacian
language: zh-CN
timezone: 'Asia/Shanghai'
url: https://blog.jacian.com
permalink: ':year/:month/:day/:hash/'
permalink_defaults: null
pretty_urls:
    trailing_index: true
    trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
    enable: true
    field: site
    exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
    enable: true
    line_number: false
    auto_detect: false
    tab_replace: ''
    wrap: true
    hljs: false
prismjs:
    enable: false
    preprocess: true
    line_number: false
    tab_replace: ''
index_generator:
    path: ''
    per_page: 10
    order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: butterfly
deploy:
    type: git
    repo: https://github.com/JacianLiu/blog-static
    branch: master
githubcalendar:
    enable: true
    enable_page: / # 表示只在根目录(首页)显示
    user: JacianLiu # 替换成你 GitHub 的用户名
    layout_id: recent-posts
    githubcalendar_html: '<div class="recent-post-item" style="width:100%;height:auto;padding:10px;"><div id="github_loading" style="width:10%;height:100%;margin:0 auto;display: block"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"  viewBox="0 0 50 50" style="enable-background:new 0 0 50 50" xml:space="preserve"><path fill="#d0d0d0" d="M25.251,6.461c-10.318,0-18.683,8.365-18.683,18.683h4.068c0-8.071,6.543-14.615,14.615-14.615V6.461z" transform="rotate(275.098 25 25)"><animateTransform attributeType="xml" attributeName="transform" type="rotate" from="0 25 25" to="360 25 25" dur="0.6s" repeatCount="indefinite"></animateTransform></path></svg></div><div id="github_container"></div></div>'
    pc_minheight: 280px
    mobile_minheight: 0px
    color: "['#ebedf0', '#fdcdec', '#fc9bd9', '#fa6ac5', '#f838b2', '#f5089f', '#c4067e', '#92055e', '#540336', '#48022f', '#30021f']"
    api: https://python-github-calendar-api.vercel.app/api
    # api: https://python-gitee-calendar-api.vercel.app/api
    calendar_js: https://cdn.jsdelivr.net/gh/Zfour/hexo-github-calendar@1.16/hexo_githubcalendar.js
# offline config passed to sw-precache.
offline:
    maximumFileSizeToCacheInBytes: 10485760 # 緩存的最大文件大小，以字節為單位
    staticFileGlobs:
        - public/**/*.{js,html,css,png,jpg,gif,svg,webp,eot,ttf,woff,woff2}
    # 靜態文件合集，如果你的站點使用了例如webp格式的文件，請將文件類型添加進去。
    stripPrefix: public
    verbose: true
    runtimeCaching:
        # CDNs - should be cacheFirst, since they should be used specific versions so should not change
        - urlPattern: /* # 如果你需要加載CDN資源，請配置該選項，如果沒有，可以不配置。
          handler: cacheFirst
          options:
              origin: https://blog.jacian.com # 可替換成你的 url
